/**
 * Mock data with deterministic seeded drift for "live" feel.
 * TODO: Replace with real APIs (DEX, news feeds, podcast RSS).
 */

import type { Ticker, NewsItem, PodcastEpisode, LearnModule, MycoSnapshot, ResearchItem } from "./types";

function seededRandom(seed: number) {
  const x = Math.sin(seed) * 10000;
  return x - Math.floor(x);
}

function drift(base: number, seed: number, range = 0.02): number {
  return base * (1 + (seededRandom(seed) - 0.5) * range);
}

export function getMockTickers(): Ticker[] {
  const now = Date.now();
  const basePrices: Record<string, number> = {
    BTC: 97500,
    ETH: 3650,
    SOL: 218,
    AVAX: 42,
    LINK: 18.5,
    UNI: 12.2,
    DOT: 8.2,
    ATOM: 12.5,
    XRP: 2.15,
    ADA: 1.08,
    DOGE: 0.38,
    LTC: 98,
    BNB: 615,
    MATIC: 0.92,
    NEAR: 7.2,
    ARB: 1.85,
    OP: 2.95,
    INJ: 38,
    TIA: 18.5,
    SUI: 3.85,
    SEI: 0.72,
    SPY: 585,
    QQQ: 495,
    DXY: 104.2,
    VIX: 14.2,
    US10Y: 4.25,
    GOLD: 2650,
    SILVER: 31.2,
    PLAT: 985,
    OIL: 78.5,
    NATGAS: 2.85,
    COPPER: 4.42,
    WHEAT: 5.68,
    CORN: 4.25,
    SOY: 11.85,
    MYCO: 0.042,
    BIOX: 0.89,
    GENE: 2.15,
    BDM: 127.5,
    AAPL: 228,
    MSFT: 415,
    NVDA: 138,
    AMZN: 198,
    GOOGL: 175,
    META: 585,
    JPM: 248,
    GS: 485,
    "BRK.B": 415,
    V: 315,
    MA: 485,
    UNH: 585,
  };
  const names: Record<string, string> = {
    BTC: "Bitcoin",
    ETH: "Ethereum",
    SOL: "Solana",
    AVAX: "Avalanche",
    LINK: "Chainlink",
    UNI: "Uniswap",
    DOT: "Polkadot",
    ATOM: "Cosmos",
    XRP: "Ripple",
    ADA: "Cardano",
    DOGE: "Dogecoin",
    LTC: "Litecoin",
    BNB: "BNB",
    MATIC: "Polygon",
    NEAR: "NEAR",
    ARB: "Arbitrum",
    OP: "Optimism",
    INJ: "Injective",
    TIA: "Celestia",
    SUI: "Sui",
    SEI: "Sei",
    SPY: "S&P 500 ETF",
    QQQ: "Nasdaq 100 ETF",
    DXY: "US Dollar Index",
    VIX: "VIX Volatility",
    US10Y: "10Y Treasury",
    GOLD: "Gold",
    SILVER: "Silver",
    PLAT: "Platinum",
    OIL: "WTI Crude",
    NATGAS: "Natural Gas",
    COPPER: "Copper",
    WHEAT: "Wheat",
    CORN: "Corn",
    SOY: "Soybeans",
    MYCO: "MYCO",
    BIOX: "BioX",
    GENE: "GeneChain",
    BDM: "BioData Index",
    AAPL: "Apple",
    MSFT: "Microsoft",
    NVDA: "NVIDIA",
    AMZN: "Amazon",
    GOOGL: "Alphabet",
    META: "Meta",
    JPM: "JPMorgan",
    GS: "Goldman Sachs",
    "BRK.B": "Berkshire",
    V: "Visa",
    MA: "Mastercard",
    UNH: "UnitedHealth",
  };
  const assetClasses: Record<string, Ticker["assetClass"]> = {
    BTC: "crypto",
    ETH: "crypto",
    SOL: "crypto",
    AVAX: "crypto",
    LINK: "crypto",
    UNI: "crypto",
    DOT: "crypto",
    ATOM: "crypto",
    XRP: "crypto",
    ADA: "crypto",
    DOGE: "crypto",
    LTC: "crypto",
    BNB: "crypto",
    MATIC: "crypto",
    NEAR: "crypto",
    ARB: "crypto",
    OP: "crypto",
    INJ: "crypto",
    TIA: "crypto",
    SUI: "crypto",
    SEI: "crypto",
    SPY: "equity",
    QQQ: "equity",
    DXY: "forex",
    VIX: "equity",
    US10Y: "forex",
    GOLD: "precious_metals",
    SILVER: "precious_metals",
    PLAT: "precious_metals",
    OIL: "commodity",
    NATGAS: "commodity",
    COPPER: "commodity",
    WHEAT: "commodity",
    CORN: "commodity",
    SOY: "commodity",
    MYCO: "bio",
    BIOX: "bio",
    GENE: "bio",
    BDM: "bio",
    AAPL: "equity",
    MSFT: "equity",
    NVDA: "equity",
    AMZN: "equity",
    GOOGL: "equity",
    META: "equity",
    JPM: "equity",
    GS: "equity",
    "BRK.B": "equity",
    V: "equity",
    MA: "equity",
    UNH: "equity",
  };

  return Object.entries(basePrices).map(([symbol, base], i) => {
    const seed = now / 60000 + i * 7;
    const price = drift(base, seed, 0.015);
    const changePct = (seededRandom(seed + 1) - 0.5) * 4;
    const sessionChangePct = (seededRandom(seed + 3) - 0.5) * 3;
    const change = (price * changePct) / 100;
    const sparkline = Array.from({ length: 24 }, (_, j) =>
      drift(price, seed + j * 13, 0.02)
    );
    return {
      id: symbol,
      symbol,
      name: names[symbol],
      assetClass: assetClasses[symbol],
      currency: "USD",
      price,
      change,
      changePct,
      sessionChangePct,
      sparkline,
      updatedAt: new Date(now - Math.floor(seededRandom(seed + 2) * 60000)).toISOString(),
    };
  });
}

export function getMockNews(): NewsItem[] {
  return [
    {
      id: "1",
      source: "Market Brief",
      title: "Solana ecosystem sees sustained developer activity",
      summary: "On-chain metrics show continued growth in Solana-based projects and DAO governance tools.",
      url: "#",
      tags: ["crypto", "solana"],
      publishedAt: new Date(Date.now() - 3600000).toISOString(),
      category: "crypto",
      relatedAssets: ["SOL"],
      catalystType: "network activity",
      impactLevel: "medium",
    },
    {
      id: "2",
      source: "Biotech Daily",
      title: "Decentralized biobanks gain traction for research data",
      summary: "Community-driven data incentives and tissue licensing models attract institutional interest.",
      url: "#",
      tags: ["biobank", "research"],
      publishedAt: new Date(Date.now() - 7200000).toISOString(),
      category: "mycodao",
      relatedAssets: ["MYCO"],
      catalystType: "biobank milestone",
      impactLevel: "high",
    },
    {
      id: "3",
      source: "Financial Times",
      title: "TradFi indices hold steady amid macro uncertainty",
      summary: "SPY and commodity markets show resilience as investors weigh inflation data.",
      url: "#",
      tags: ["markets", "spy"],
      publishedAt: new Date(Date.now() - 10800000).toISOString(),
      category: "markets",
      relatedAssets: ["SPY", "GOLD"],
      catalystType: "macro",
      impactLevel: "medium",
    },
    {
      id: "4",
      source: "DAO Weekly",
      title: "Governance tokens and citizen science rewards",
      summary: "How token-based incentives support community research and environmental monitoring.",
      url: "#",
      tags: ["governance", "rewards"],
      publishedAt: new Date(Date.now() - 14400000).toISOString(),
      category: "mycodao",
      relatedAssets: ["MYCO"],
      catalystType: "proposal",
      impactLevel: "medium",
    },
    {
      id: "5",
      source: "Crypto Pulse",
      title: "Bitcoin inscriptions expand to new use cases",
      summary: "Proof of Invention and IP tokenization gain adoption on Ethereum and Solana.",
      url: "#",
      tags: ["bitcoin", "inscriptions"],
      publishedAt: new Date(Date.now() - 18000000).toISOString(),
      category: "crypto",
      relatedAssets: ["BTC", "ETH", "SOL"],
      catalystType: "partnership",
      impactLevel: "low",
    },
    {
      id: "6",
      source: "Reuters",
      title: "Fed signals data-dependent path on rates",
      summary: "Central bank officials emphasize inflation and labor market readings.",
      url: "#",
      tags: ["fed", "rates"],
      publishedAt: new Date(Date.now() - 21600000).toISOString(),
      category: "markets",
      relatedAssets: ["DXY", "GOLD"],
      catalystType: "regulation",
      impactLevel: "high",
    },
    {
      id: "7",
      source: "Bloomberg",
      title: "Tech earnings beat estimates; NVDA leads",
      summary: "Major tech names report strong results amid AI demand.",
      url: "#",
      tags: ["earnings", "tech"],
      publishedAt: new Date(Date.now() - 25200000).toISOString(),
      category: "markets",
      relatedAssets: ["NVDA"],
      catalystType: "earnings",
      impactLevel: "high",
    },
    {
      id: "8",
      source: "CoinDesk",
      title: "Ethereum L2s see record activity post-Dencun",
      summary: "Arbitrum, Optimism, Base report surge in daily transactions.",
      url: "#",
      tags: ["ethereum", "l2"],
      publishedAt: new Date(Date.now() - 28800000).toISOString(),
      category: "crypto",
      relatedAssets: ["ETH"],
      catalystType: "network activity",
      impactLevel: "medium",
    },
    {
      id: "9",
      source: "MycoDAO",
      title: "Biobank incentives program reaches 50K samples",
      summary: "Community-driven data contributions exceed milestone.",
      url: "#",
      tags: ["biobank", "milestone"],
      publishedAt: new Date(Date.now() - 32400000).toISOString(),
      category: "mycodao",
      relatedAssets: ["MYCO"],
      catalystType: "biobank milestone",
      impactLevel: "high",
    },
    {
      id: "10",
      source: "WSJ",
      title: "Dollar strength weighs on commodities",
      summary: "DXY rally pressures oil, copper, and precious metals.",
      url: "#",
      tags: ["dxy", "commodities"],
      publishedAt: new Date(Date.now() - 36000000).toISOString(),
      category: "markets",
      relatedAssets: ["DXY", "OIL", "COPPER", "GOLD"],
      catalystType: "macro",
      impactLevel: "medium",
    },
    {
      id: "11",
      source: "The Block",
      title: "Solana DeFi TVL crosses $5B",
      summary: "Jupiter, Raydium lead growth in Solana ecosystem.",
      url: "#",
      tags: ["solana", "defi"],
      publishedAt: new Date(Date.now() - 39600000).toISOString(),
      category: "crypto",
      relatedAssets: ["SOL"],
      catalystType: "network activity",
      impactLevel: "medium",
    },
    {
      id: "12",
      source: "MycoDAO",
      title: "Governance proposal: Expand research grants pool",
      summary: "Community vote to increase MYCO allocation for Q2.",
      url: "#",
      tags: ["governance", "grants"],
      publishedAt: new Date(Date.now() - 43200000).toISOString(),
      category: "mycodao",
      relatedAssets: ["MYCO"],
      catalystType: "grant",
      impactLevel: "high",
    },
  ];
}

export function getMockPodcasts(): PodcastEpisode[] {
  return [
    {
      id: "1",
      title: "Governance and Funding in DAOs",
      show: "MycoDAO Podcast",
      description: "How governance tokens fund community grants and research incentives.",
      audioUrl: "/audio/sample.mp3",
      durationSec: 1842,
      publishedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: "2",
      title: "Biobank Data and Tissue Licensing",
      show: "MycoDAO Podcast",
      description: "Exploring decentralized biobank storage and licensing models.",
      audioUrl: "/audio/sample.mp3",
      durationSec: 2100,
      publishedAt: new Date(Date.now() - 172800000).toISOString(),
    },
    {
      id: "3",
      title: "Financial Literacy: Reading a Ticker",
      show: "Learn Pulse",
      description: "Understanding price, change, and sparklines in market data.",
      audioUrl: "/audio/sample.mp3",
      durationSec: 900,
      publishedAt: new Date(Date.now() - 259200000).toISOString(),
    },
    {
      id: "4",
      title: "DeFi Basics: Liquidity Pools",
      show: "Crypto Explained",
      description: "How AMMs and liquidity pools work.",
      audioUrl: "/audio/sample.mp3",
      durationSec: 2400,
      publishedAt: new Date(Date.now() - 302400000).toISOString(),
    },
    {
      id: "5",
      title: "Tissue Licensing Models",
      show: "Biotech Weekly",
      description: "Licensing frameworks for research tissue samples.",
      audioUrl: "/audio/sample.mp3",
      durationSec: 2100,
      publishedAt: new Date(Date.now() - 345600000).toISOString(),
    },
    {
      id: "6",
      title: "Macro Markets: Fed and Rates",
      show: "Markets Daily",
      description: "How central bank policy affects asset prices.",
      audioUrl: "/audio/sample.mp3",
      durationSec: 1800,
      publishedAt: new Date(Date.now() - 388800000).toISOString(),
    },
    {
      id: "7",
      title: "Tokenomics Deep Dive",
      show: "MycoDAO Podcast",
      description: "Supply, distribution, and governance token design.",
      audioUrl: "/audio/sample.mp3",
      durationSec: 2700,
      publishedAt: new Date(Date.now() - 432000000).toISOString(),
    },
    {
      id: "8",
      title: "Citizen Science and Web3",
      show: "Research Pulse",
      description: "Community-driven research and data incentives.",
      audioUrl: "/audio/sample.mp3",
      durationSec: 1950,
      publishedAt: new Date(Date.now() - 475200000).toISOString(),
    },
  ];
}

export function getMockLearn(): LearnModule[] {
  return [
    {
      id: "1",
      title: "What is a Ticker?",
      level: "beginner",
      readingTimeMin: 3,
      summary: "Learn how to read price symbols and understand market data.",
      tags: ["basics", "markets"],
      contentMd: "# What is a Ticker?\n\nA ticker symbol is a unique identifier for a traded asset.",
    },
    {
      id: "2",
      title: "Governance Tokens Explained",
      level: "intermediate",
      readingTimeMin: 5,
      summary: "How governance tokens fund DAOs and community initiatives.",
      tags: ["governance", "crypto"],
      contentMd: "# Governance Tokens\n\nGovernance tokens enable voting and funding allocation.",
    },
    {
      id: "3",
      title: "Biobank Incentives and Data",
      level: "advanced",
      readingTimeMin: 7,
      summary: "Token-based incentives for biobank storage and research data.",
      tags: ["biobank", "data"],
      contentMd: "# Biobank Incentives\n\nCommunity-driven data incentives support research.",
    },
    {
      id: "4",
      title: "Reading Sparklines",
      level: "beginner",
      readingTimeMin: 2,
      summary: "How to interpret mini-charts in market data.",
      tags: ["basics", "charts"],
      contentMd: "# Sparklines\n\nSparklines show price trends at a glance.",
    },
    { id: "5", title: "Understanding Market Cap", level: "beginner", readingTimeMin: 4, summary: "Market cap and circulating supply.", tags: ["basics"], contentMd: "# Market Cap\n\nMarket cap = price × supply." },
    { id: "6", title: "Volatility and Risk", level: "intermediate", readingTimeMin: 5, summary: "Measuring and managing volatility.", tags: ["risk"], contentMd: "# Volatility\n\nVolatility measures price swings." },
    { id: "7", title: "DeFi Yield Basics", level: "intermediate", readingTimeMin: 6, summary: "Staking, lending, and liquidity provision.", tags: ["defi"], contentMd: "# DeFi Yield\n\nYield from staking and lending." },
    { id: "8", title: "Token Vesting", level: "intermediate", readingTimeMin: 4, summary: "Lock-ups and vesting schedules.", tags: ["tokens"], contentMd: "# Vesting\n\nVesting controls token release." },
    { id: "9", title: "Biobank Data Standards", level: "advanced", readingTimeMin: 8, summary: "Metadata and interoperability for research data.", tags: ["biobank"], contentMd: "# Data Standards\n\nStandards for biobank data." },
    { id: "10", title: "Governance Voting", level: "intermediate", readingTimeMin: 5, summary: "Proposals, quorum, and delegation.", tags: ["governance"], contentMd: "# Voting\n\nHow DAO voting works." },
    { id: "11", title: "Reading Order Books", level: "advanced", readingTimeMin: 6, summary: "Bid/ask depth and market structure.", tags: ["markets"], contentMd: "# Order Books\n\nOrder book structure." },
    { id: "12", title: "Research Data Incentives", level: "advanced", readingTimeMin: 7, summary: "Token rewards for data contribution.", tags: ["research", "incentives"], contentMd: "# Incentives\n\nData contribution rewards." },
  ];
}

export function getMockResearch(): ResearchItem[] {
  return [
    {
      id: "r1",
      title: "Q1 Community Grants: 12 projects funded",
      source: "MycoDAO",
      summary: "Ecosystem grants support biobank data and citizen science.",
      category: "ecosystem",
      publishedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: "r2",
      title: "Science funding round opens March 1",
      source: "MycoDAO",
      summary: "Apply for research incentives and tissue licensing.",
      category: "funding",
      publishedAt: new Date(Date.now() - 172800000).toISOString(),
    },
    {
      id: "r3",
      title: "Biobank activity: +23% samples indexed",
      source: "MycoDAO",
      summary: "Decentralized storage and metadata growth.",
      category: "biobank",
      publishedAt: new Date(Date.now() - 259200000).toISOString(),
    },
    {
      id: "r4",
      title: "New tissue licensing pilot with 3 labs",
      source: "MycoDAO",
      summary: "Expanded biobank partnerships for research data.",
      category: "ecosystem",
      publishedAt: new Date(Date.now() - 345600000).toISOString(),
    },
    {
      id: "r5",
      title: "Governance vote: Grant allocation Q2",
      source: "MycoDAO",
      summary: "Community decides on next funding round priorities.",
      category: "funding",
      publishedAt: new Date(Date.now() - 432000000).toISOString(),
    },
    { id: "r6", title: "Lab partnership: Stanford biobank pilot", source: "MycoDAO", summary: "Pilot program for tissue metadata standards.", category: "ecosystem", publishedAt: new Date(Date.now() - 518400000).toISOString() },
    { id: "r7", title: "Q1 treasury report published", source: "MycoDAO", summary: "MYCO holdings and allocation breakdown.", category: "funding", publishedAt: new Date(Date.now() - 604800000).toISOString() },
    { id: "r8", title: "Samples indexed: 48K milestone", source: "MycoDAO", summary: "Decentralized biobank reaches new high.", category: "biobank", publishedAt: new Date(Date.now() - 691200000).toISOString() },
    { id: "r9", title: "New proposal: Research grant criteria", source: "MycoDAO", summary: "Updated eligibility for community grants.", category: "funding", publishedAt: new Date(Date.now() - 777600000).toISOString() },
    { id: "r10", title: "Science funding round closes March 15", source: "MycoDAO", summary: "Final applications for Q2 research grants.", category: "ecosystem", publishedAt: new Date(Date.now() - 864000000).toISOString() },
  ];
}

export function getMockMycoSnapshot(): MycoSnapshot {
  const seed = Date.now() / 60000;
  const price = 0.042 * (1 + (seededRandom(seed) - 0.5) * 0.03);
  const changePct = (seededRandom(seed + 1) - 0.5) * 6;
  return {
    price,
    changePct,
    supply: 210_000_000,
    chain: "Solana",
    links: {
      tokenPage: "/token",
      governanceUrl: "/token#governance",
      buyUrl: "#",
    },
    updatedAt: new Date().toISOString(),
    researchFunding: {
      grantPoolMyco: 2_450_000,
      grantsDeployedMyco: 1_820_000,
      activeProposals: 7,
      votesToday: 342,
      biobankIncentivesMyco: 185_000,
      activeResearchProjects: 12,
      samplesIndexed: 48_250,
    },
    biobank: {
      samplesIndexed: 48_250,
      labsParticipating: 14,
      dataContributions: 2_340,
    },
    governance: {
      activeProposals: 7,
      votingProgressPct: 62,
      grantApprovals: 3,
    },
  };
}
